### ISSUE TITLE
test dataset are not initialized

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#200]
After the sudden move of all tests datasets definition from pw to pwem, the following command fails:

```
azazello@debian:~/soft/scipion3$ scipion3 tests --grep eman --run
Scipion v3.0.7 - Eugenius
Running tests....
>>>> xmipp3
>>>> atlas
>>>> bamfordlab
>>>> bsoft
>>>> ccp4
>>>> cryoef
>>>> cryodrgn
>>>> emxlib
>>>> fsc3d
>>>> gautomatch
>>>> imagic
>>>> localrec
>>>> locscale
>>>> motioncorr
>>>> phenix
>>>> resmap
>>>> sidesplitter
>>>> sphire
>>>> spider
>>>> topaz
>>>> chimera
>>>> eman2
python3 /home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_run_tests.py    eman2.tests.test_protocols_eman.TestEmanTiltValidate
Running tests....
Creating project at:  /home/azazello/ScipionUserData/projects/TestEmanTiltValidate/project.sqlite
[   FAILED ] TestEmanTiltValidate.setUpClass

Traceback (most recent call last):
  File "/home/azazello/soft/miniconda3/envs/.scipion3env/lib/python3.8/unittest/suite.py", line 163, in _handleClassSetUp                                                  
    setUpClass()                                                                                                                                                           
  File "/home/azazello/soft/scipion-em-plugins/scipion-em-eman2/eman2/tests/test_protocols_eman.py", line 263, in setUpClass                                               
    cls.dataset = DataSet.getDataSet('eman')                                                                                                                               
  File "/home/azazello/soft/scipion3/scipion-pyworkflow/pyworkflow/tests/tests.py", line 57, in getDataSet                                                                 
    assert name in cls._datasetDict, "Dataset: %s dataset doesn't exist." % name                                                                                           
AssertionError: Dataset: eman dataset doesn't exist.
``` 

Individual tests still work though.

**Comment by pconesa** [comment]
I should have warned you. Datasets were moved to scipion-em and we need a
small change in scipion-app. Git pull of scipion app should fix it

**Comment by azazellochg** [comment]
I have done git pull in all repos before creating this issue.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: ***@***.***

**Comment by pconesa** [comment]
You are right! the --run has a different behaviour. I need to look at 
this more in details. Thanks as always!
