### ISSUE TITLE
pwem.tests.data.test_data.TestImageHandler fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#26]
```
[   FAILED ] TestImageHandler.test_truncateMask

Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/azazello/soft/scipion3/scipion-em/pwem/tests/data/test_data.py", line 275, in test_truncateMask
    self.assertEqual(ih.getDimensions(outFn), EXPECTED_SIZE)
  File "/usr/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.8/unittest/case.py", line 1129, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/usr/lib/python3.8/unittest/case.py", line 1100, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Tuples differ: (1124073472, 1124073472, 1182794752, 1) != (128, 128, 128, 1)

First differing element 0:
1124073472
128

- (1124073472, 1124073472, 1182794752, 1)
+ (128, 128, 128, 1)
```

**Comment by azazellochg** [comment]
I think it must be xmipp imageHandler problem, since in many tests I get e.g. nonsense numbers for xyz dimensions of vol/spi volumes

**Comment by azazellochg** [comment]
Should be fine now with last fixes

**Comment by dmaluenda** [comment]
Oh, thanks @azazellochg !

**Comment by azazellochg** [comment]
The problem traced back: getHome returns nothing when convertImage inside eman/convert/convert.py is called. Fix:
```
Plugin._defineVariables()
 proc = Plugin.createEmanProcess.....
```
@pconesa is this a good way?

**Comment by pconesa** [comment]
I'll have a look. Is good if it fixes it...but I find it is a bad design of the core if you need to do that. Let me try to see why variables are not initialized automatically.

**Comment by pconesa** [comment]
I see what is happening here. When running tests, Plugins are not initialized and defineVariables is not happening. I'll find a place to do this initialization for all tests.

**Comment by delarosatrevin** [comment]
This happened before in the register plugin call.
