### ISSUE TITLE
No import jobs available

### ISSUE THREAD

**Issue by helgepat** [scipion-em/scipion-em#287]
Hi,
I installed Scipion 3.0 on our workstation running Ubuntu 20.04. I performed the basic tests and they all worked.
My problem is that I do not have anything listed under the "Import" section.
Here is a picture of how it looks to me:
![picture](https://user-images.githubusercontent.com/97705752/150324987-d1d321d3-0d3f-4d3e-b130-d66f747aaa03.png)

I reinstalled and ran from that terminal and got this message:

> error when importing from xmipp3.protocols: cannot import name 'isMdEmpty' from 'xmipp3.base' (/home/XXX/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/base.py)
   File "/home/XXX/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_ctf_micrographs.py", line 44, in <module>
   Check the plugin manager (Configuration->Plugins in Scipion manager window) 
   or use 'scipion installp --help --checkUpdates' in the command line to check for upgrades,
   it could be a versions compatibility issue.

I would be happy about input on the matter, thank you in advance!

**Comment by pconesa** [comment]
It seems xmipp didn't compile properly. 
What gives you 

scipion3 installb

**Comment by helgepat** [comment]
Here you go:

scipion3 installb
Scipion v3.0.10 - Eugenius
usage: scipion installb  [-h] binName1 binName2-1.2.3 binName3 ...

positional arguments:
  binName(s)  The name(s) of the bins we want install, optionally with 
              version in the form name-version. If no version is specified,
              will install the last one.

optional arguments:
  -h, --help  show help
  -j j        Number of CPUs to use for compilation 

Example: scipion installb ctffind4 eman-2.3

Available binaries: ([ ] not installed, [X] seems already installed)

deepLearningToolkit      0.2     [ ]     
maxit                    10.1    [ ]     
xmippSrc                 3.21.09.0[X]

**Comment by helgepat** [comment]
I re-ran the basic tests as stated (with "scipion3"):
<h3><a class="toc-backref" href="https://scipion-em.github.io/docs/docs/scipion-modes/verify-installation.html#id4">Basic tests</a><a class="headerlink" href="https://scipion-em.github.io/docs/docs/scipion-modes/verify-installation.html#basic-tests" title="Permalink to this headline"></a></h3>
<div class="wy-table-responsive">

Plugins | Core, Xmipp, Relion
-- | --
  | scipion tests pyworkflowtests.tests.test_object.TestObject
  | scipion tests pyworkflowtests.tests.test_mappers
  | scipion tests pwem.tests.data.test_data
  | scipion tests xmipp3.tests.test_convert_xmipp
  | scipion tests relion.tests.test_convert_relion

</div>
This gives me two failures for missing modules "eman2" and "relion"
I assumed that are harmless for my problem, but does Scipion use eman2 for import jobs?
Relion I do not want to install, as we already have it installed separately.

"scipion3 tests pwem.tests.data.test_data"

[   FAILED ] TestImageHandler.test_convertMicrographs

Traceback (most recent call last):
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/plugin.py", line 296, in _tryImportFromPlugin
    output = getattr(importlib.import_module(module), submodule)
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'eman2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/tests/data/test_data.py", line 255, in test_convertMicrographs
    ih.convert(micFn, outFn)
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pwem/emlib/image/image_handler.py", line 158, in convert
    convertImage = Domain.importFromPlugin('eman2.convert',
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/plugin.py", line 305, in importFromPlugin
    output = _tryImportFromPlugin(objects)
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/plugin.py", line 302, in _tryImportFromPlugin
    Domain.__pluginNotFound(plugName, errMsg, doRaise)
  File "/home/agwilson/Software/miniconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/plugin.py", line 448, in __pluginNotFound
    raise Exception("\n\n" + raiseMsg)
Exception: 

 > error when importing from eman2: No module named 'eman2'
   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
   Check the plugin manager (Configuration->Plugins in Scipion manager window) 
   or use 'scipion installp --help --checkUpdates' in the command line to check for upgrades,
   it could be a versions compatibility issue.

**Comment by helgepat** [comment]
Hi again,
I just solved the issue by installing the "eman2" and "xmipp2" plugins through the plugin manager.
I guess this issue can be closed.
