### ISSUE TITLE
guessCudaVersion error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#457]
Hi,

I have a problem:

CUDA_LIB = /public/EM/CUDA/cuda-11.4/lib64

However, cuda-11.4 is a symlink to 11.4.safe folder. I get this error:

```
Traceback (most recent call last):
  File "/public/EM/Scipion/scipion-dev/scipion-app/scipion/__main__.py", line 499, in <module>
    main()
  File "/public/EM/Scipion/scipion-dev/scipion-app/scipion/__main__.py", line 323, in main
    main(sys.argv[2:])
  File "/public/EM/Scipion/scipion-dev/scipion-app/scipion/scripts/config.py", line 99, in main
    plugin._defineVariables()
  File "/public/EM/Scipion/scipion-dev/scipion-em-plugins/scipion-em-aretomo/aretomo/__init__.py", line 53, in _defineVariables
    cudaVersion = cls.guessCudaVersion(ARETOMO_CUDA_LIB)
  File "/public/EM/Scipion/scipion-dev/scipion-em/pwem/__init__.py", line 168, in guessCudaVersion
    return cls.getVersionFromVariable(variable, default=default, pattern="cuda")
  File "/public/EM/Scipion/scipion-dev/scipion-em/pwem/__init__.py", line 181, in getVersionFromVariable
    return cls.getVersionFromPath(value, default= default, pattern=pattern)
  File "/public/EM/Scipion/scipion-dev/scipion-em/pwem/__init__.py", line 209, in getVersionFromPath
    return parse_version(versionStr)
  File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '11.4.safe'
Error at main: Invalid version: '11.4.safe'
```

I don't know why is it resolving symlinks?

**Comment by pconesa** [comment]
We are resolving links cause cuda installer ask about linking /usr/local/cuda to a real cuda path.... and CUDA_LIB could be /usr/local/cuda/lib64

**Comment by pconesa** [comment]
Maybe we can use regex instead

**Comment by azazellochg** [comment]
I see, hm..
