### ISSUE TITLE
tif  header reader changed?

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#475]
Import test movies now fail with:
```
[   FAILED ] TestImportMovies.test_tif


Traceback (most recent call last):
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/gsharov/soft/scipion3/scipion-em/pwem/tests/protocols/test_protocols_import_movies.py", line 100, in test_tif
    self._checkOutput(protMovieImport, args, size=1, dim=(7676, 7420, 38))
  File "/home/gsharov/soft/scipion3/scipion-em/pwem/tests/protocols/test_protocols_import_movies.py", line 72, in _checkOutput
    self.assertEqual(dim, (x, y, n))
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 1129, in assertTupleEqual
    self.assertSequenceEqual(tuple1, tuple2, msg, seq_type=tuple)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 1100, in assertSequenceEqual
    self.fail(msg)
  File "/home/gsharov/soft/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: Tuples differ: (7676, 7420, 38) != (7420, 7676, 38)
```

pwem.tests.data.test_data.TestImageHandler fails with the same error.

Both eman2 and imod report the header of data/tests/movies/c3-adp-se-xyz-0228_200.tif as 7676 x 7420

**Comment by azazellochg** [comment]
this is the mess I'm getting when processing tif movies now
![image](https://github.com/scipion-em/scipion-em/assets/6952870/007c284f-4d24-4b54-8e98-09818c7937e0)

**Comment by azazellochg** [comment]
I was able to trace this to this commit: https://github.com/scipion-em/scipion-em/commit/c1e840d49b8d422a1a47911b95ec0e6adf1a6c3b which changed tif reader from xmipp to tifffile

**Comment by azazellochg** [comment]
The current code defines x/y and from the page shape which has YX axes - that's already wrong.
```
from tifffile import TiffFile
tif = TiffFile("FoilHole_17022306_Data_16990740_16990742_20210518_133741_fractions.tiff")
len(tif.pages)
73
page = tif.pages[0]
page.shape
(4092, 5760)
page.axes
'YX'

```

Xmipp reader gets x/y from width/length respectively:
```
page.imagewidth
5760
page.imagelength
4092
```

**Comment by azazellochg** [comment]
More info.. this was already found and fixed in https://github.com/scipion-em/scipion-em/pull/447/commits/aa20594bc786addc0711ee2a2cd1bc92e392333f
