### ISSUE TITLE
metadata viewer issue with Averages

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#505]
The new viewer cannot display Averages:

```
Traceback (most recent call last):
File "/public/EM/Scipion/miniconda3/envs/scipion3/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
return self.func(*args)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols_extra.py", line 144, in <lambda>
return lambda: self._visualizeObject(viewer, obj)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/gui/project/viewprotocols_extra.py", line 99, in _visualizeObject
viewer.visualize(obj, windows=self.parent.window)
File "/public/EM/Scipion/scipion-dev/scipion-pyworkflow/pyworkflow/viewer.py", line 156, in visualize
view.show()
File "/public/EM/Scipion/scipion-dev/scipion-em/pwem/viewers/mdviewer/viewer.py", line 48, in show
config = self.getVisibleAndOrderLabels()
File "/public/EM/Scipion/scipion-dev/scipion-em/pwem/viewers/mdviewer/viewer.py", line 57, in getVisibleAndOrderLabels
visible = config[VISIBLE] if VISIBLE in config else ''
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by pconesa** [comment]
This might be fixed?

**Comment by azazellochg** [comment]
Yes!! Thank you
