### ISSUE TITLE
failing to install xmipp-2 plugin

### ISSUE THREAD

**Issue by shahpnmlab** [scipion-em/scipion-em#551]
Hi Team, 
I want to use the scipion-local-rec workflow for which I need Xmipp as a dependency. However, when i try to install it via the commandline, I get the following error message
```
./scipion3 installp -p scipion-em-xmipp2
Scipion v3.7.0 - Eugenius

 >>> WARNING: XmippImage library not found!
  > Please install Xmipp to get full functionality for cryo electron microscopy workflows. Otherwise ignore this.
(Configuration->Plugins->scipion-em-xmipp -> expand, in Scipion plugin manager window)


Set SCIPION_CANCEL_XMIPP_BINDING_WARNING = True to cancel this message.

Installing scipion-em-xmipp2 ...
/home/pranav/software/miniforge3/envs/scipion3/bin/python -m pip install scipion-em-xmipp2==3.0.1
Collecting scipion-em-xmipp2==3.0.1
  Using cached scipion_em_xmipp2-3.0.1-py3-none-any.whl.metadata (763 bytes)
Requirement already satisfied: scipion-em-tomo in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em-xmipp2==3.0.1) (3.9.2)
Requirement already satisfied: mrcfile<=1.4.3,>=1.4.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.4.3)
Requirement already satisfied: scipion-em>=3.9.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.9.3)
Requirement already satisfied: numpy>=1.16.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from mrcfile<=1.4.3,>=1.4.0->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.26.1)
Requirement already satisfied: scipion-pyworkflow>=3.4.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.10.5)
Requirement already satisfied: emtable>=0.0.14 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (0.0.14)
Requirement already satisfied: scipy<=1.10.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.10.0)
Requirement already satisfied: biopython==1.81 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.81)
Requirement already satisfied: tifffile==2023.9.26 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2023.9.26)
Requirement already satisfied: bibtexparser<=1.4.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.4.1)
Requirement already satisfied: psutil<=5.9.6 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (5.9.6)
Requirement already satisfied: tkcolorpicker in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2.1.3)
Requirement already satisfied: distro<=1.8 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.8.0)
Requirement already satisfied: importlib-metadata<=6.8.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (6.8.0)
Requirement already satisfied: configparser==6.0.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (6.0.0)
Requirement already satisfied: pillow==10.1.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (10.1.0)
Requirement already satisfied: requests==2.31.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2.31.0)
Requirement already satisfied: matplotlib==3.8.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.8.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2.9.0.post0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from requests==2.31.0->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from requests==2.31.0->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from requests==2.31.0->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from requests==2.31.0->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (2024.8.30)
Requirement already satisfied: zipp>=0.5 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from importlib-metadata<=6.8.0->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (3.21.0)
Requirement already satisfied: six>=1.5 in /home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib==3.8.1->scipion-pyworkflow>=3.4.0->scipion-em>=3.9.1->scipion-em-tomo->scipion-em-xmipp2==3.0.1) (1.17.0)
Using cached scipion_em_xmipp2-3.0.1-py3-none-any.whl (32 kB)
Installing collected packages: scipion-em-xmipp2
Successfully installed scipion-em-xmipp2-3.0.1
Done (0.41 seconds)
Installing xmipp2-2.4 ...
  Skipping command: wget -nv -c -O /home/pranav/software/scipion3/software/em/Xmipp-2.4-src.tgz.part https://scipion.cnb.csic.es/downloads/scipion/software/em/Xmipp-2.4-src.tgz
mv -v /home/pranav/software/scipion3/software/em/Xmipp-2.4-src.tgz.part /home/pranav/software/scipion3/software/em/Xmipp-2.4-src.tgz
  All targets ['/home/pranav/software/scipion3/software/em/Xmipp-2.4-src.tgz'] exist.
  Skipping command: tar -xf Xmipp-2.4-src.tgz
  All targets ['/home/pranav/software/scipion3/software/em/Xmipp-2.4-src'] exist.
cd /home/pranav/software/scipion3/software/em/Xmipp-2.4-src
./scons.configure && ./scons.compile -j 8
** Use scons.configure --help to show a help message
./scons.configure: line 6: python2: command not found
ERROR: File or folder '/home/pranav/software/scipion3/software/em/Xmipp-2.4-src/lib/libXmippRecons_Interface.so' not found after running './scons.configure && ./scons.compile -j 8'.
```
When trying to install xmipp the program is unable to compile scikit-llearn
```
 Building wheel for scikit-learn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      /tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Partial import of sklearn during the build process.
      /tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/setup.py:123: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.command.build_ext import build_ext  # noqa
      Traceback (most recent call last):
        File "/tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/sklearn/_build_utils/__init__.py", line 32, in _check_cython_version
          import Cython
      ModuleNotFoundError: No module named 'Cython'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/setup.py", line 303, in <module>
          setup_package()
        File "/tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/setup.py", line 299, in setup_package
          setup(**metadata)
        File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "/tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/setup.py", line 180, in configuration
          _check_cython_version()
        File "/tmp/pip-install-475eaobw/scikit-learn_977ebfba45224c13a1c96a0e8e4f958f/sklearn/_build_utils/__init__.py", line 35, in _check_cython_version
          raise ModuleNotFoundError(message)
      ModuleNotFoundError: Please install Cython with a version >= 0.28.5 in order to build a scikit-learn from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-learn)
Done (1.58 seconds)
Warning: couldn't find Plugin for scipion-em-xmipp
Dirname: None
Traceback (most recent call last):
  File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages/scipion/__main__.py", line 507, in <module>
    main()
  File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages/scipion/__main__.py", line 314, in main
    installPluginMethods()
  File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.10/site-packages/scipion/install/install_plugin.py", line 235, in installPluginMethods
    plugin.getPluginClass()._defineVariables()
AttributeError: 'NoneType' object has no attribute '_defineVariables'
Error at main: 'NoneType' object has no attribute '_defineVariables'
```
Please can you advise on how I can move forward?

Best,
Pranav

**Comment by azazellochg** [comment]
Hi Pranav,

I'm not sure how you managed to find xmipp2 plugin but it was deprecated long ago.  Please see https://i2pc.github.io/docs/Installation/Installations/index.html for xmipp3

**Comment by shahpnmlab** [comment]
Hi Grigory, T
hanks for pointing me in the right direction. Having installed xmipp now, I still cannot run the the local-rec protocol on account of `xmipp_image_operate` is unable to locate its dependent libraries
```
00001:   xmipp_image_operate: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
00002:   Couldn't run the code in a thread.
00003:   Traceback (most recent call last):
00004:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 156, in run
00005:       self.step._run()  # not self.step.run() , to avoid race conditions
00006:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 257, in _run
00007:       resultFiles = self._runFunc()
00008:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 253, in _runFunc
00009:       return self._func(*self._args)
00010:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/localrec/protocols/protocol_localized_stitch.py", line 381, in maskVolume
00011:       self.runJob(program, args)
00012:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1545, in runJob
00013:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00014:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 68, in runJob
00015:       process.runJob(log, programName, params,
00016:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 56, in runJob
00017:       return runCommand(command, env=env, cwd=cwd, executable=executable)
00018:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 71, in runCommand
00019:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00020:     File "/home/pranav/software/miniforge3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00021:       raise CalledProcessError(retcode, cmd)
00022:   subprocess.CalledProcessError: Command ' xmipp_image_operate -i Runs/000002_ProtImportVolumes/extra/import_blockA_b4.mrc:mrc --mult Runs/000112_ProtLocalizedStich/tmp/output_mask_1.vol -o Runs/000112_ProtLocalizedStich/tmp/output_volume_masked_1.vol' returned non-zero exit status 127.
00023:   Protocol failed: Command ' xmipp_image_operate -i Runs/000002_ProtImportVolumes/extra/import_blockA_b4.mrc:mrc --mult Runs/000112_ProtLocalizedStich/tmp/output_mask_1.vol -o Runs/000112_ProtLocalizedStich/tmp/output_volume_masked_1.vol' returned non-zero exit status 127.
```
I am really at loss as I expecting Scipion3 would set the appropriate env variable upon launch?

This is my conf file for scipion if it is any help

```
────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [PYWORKFLOW]
   2   │ CONDA_ACTIVATION_CMD = eval "$(/home/pranav/software/miniforge3/bin/conda shell.bash hook)"
   3   │ SCIPION_STEPS_CHECK_SEC = 5
   4   │ SCIPION_GUI_REFRESH_INITIAL_WAIT = 5
   5   │ SCIPION_MAIN_COLOR = Firebrick
   6   │ SCIPION_FONT_NAME = Helvetica
   7   │ SCIPION_ICON_ZOOM = 50
   8   │ SCIPION_LOG_LEVEL = INFO
   9   │ SCIPION_SPRITES_FILE = ~/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/resources/sprites.png
  10   │ NO_COLOR = 
  11   │ SCIPION_UPDATE_SET_ATTEMPTS = 3
  12   │ SCIPION_LOG = ~/ScipionUserData/logs/scipion.log
  13   │ SCIPION_FONT_SIZE = 10
  14   │ SCIPION_CANCEL_FASTCOPY = False
  15   │ SCIPION_URL_SOFTWARE = https://scipion.cnb.csic.es/downloads/scipion/software
  16   │ SCIPION_URL_TESTDATA = https://scipion.cnb.csic.es/downloads/scipion/data/tests
  17   │ SCIPION_DOMAIN = pwem
  18   │ SCIPION_GUI_REFRESH_IN_THREAD = False
  19   │ SCIPION_TESTS_OUTPUT = ~/ScipionUserData/Tests
  20   │ SCIPION_PLUGIN_REPO_URL = https://scipion.i2pc.es/getplugins/
  21   │ _Config__defaultSpritesFile = ~/software/miniforge3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/resources/sprites.png
  22   │ SCIPION_LOG_FORMAT = %%(message)s
  23   │ SCIPION_TESTS_CMD = scipion3 tests
  24   │ SCIPION_CONTRAST_COLOR = cyan
  25   │ SCIPION_LOGS = ~/ScipionUserData/logs
  26   │ SCIPION_TESTS = ${SCIPION_HOME}/data/tests
  27   │ SCIPION_USE_QUEUE = False
  28   │ SCIPION_BG_COLOR = white
  29   │ SCIPION_DEFAULT_EXECUTION_ACTION = 1
  30   │ SCIPION_PRIORITY_PACKAGE_LIST = pwem tomo pwchem
  31   │ SCIPION_TEXT_EDITOR = 
  32   │ SCIPION_MAPPER_USE_TEMPLATE = True
  33   │ SCIPION_NOTIFY = True
  34   │ SCIPION_HOME_DEFINED = True
  35   │ SCIPION_URL = https://scipion.cnb.csic.es/downloads/scipion
  36   │ SCIPION_TEST_NOSYNC = False
  37   │ SCIPION_NOTES_FILE = notes.txt
  38   │ SCIPION_USER_DATA = ~/ScipionUserData
  39   │ SCIPION_SHOW_TEXT_IN_TOOLBAR = True
  40   │ SCIPION_SOFTWARE = ${SCIPION_HOME}/software
  41   │ SCIPION_UPDATE_SET_ATTEMPT_WAIT = 2
  42   │ SCIPION_SUPPORT_EMAIL = scipion@cnb.csic.es
  43   │ SCIPION_GUI_CANCEL_AUTO_REFRESH = False
  44   │ 
  45   │ [PLUGINS]
  46   │ XMIPP_CUDA_LIB = /usr/local/cuda/lib64
  47   │ EM_ROOT = software/em
  48   │ XMIPP_HOME = %(EM_ROOT)s/xmipp
  49   │ XMIPP_CUDA_BIN = /usr/local/cuda/bin
  50   │ MAXIT_HOME = %(EM_ROOT)s/maxit-10.1
```

**Comment by azazellochg** [comment]
Hi, looks like the installation wasn't successful. I suggest to ask xmipp team on discord as they don't monitor this repo
