### ISSUE TITLE
Dimensions' size cannot be zero nor negative.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em#87]
@mmmtnez  reported this at #86 

Test: scipion3 test --grep phenix --run

There is only one test failing due to the failing of the import volume protocol (scipion3 tests phenix.tests.test_protocol_validation_cryoem.TestValCryoEM.testValCryoEMFFromVolumeAndPDB4) Here you are the problem:

ERROR running protocol import volume hemoglobin
set origin 0.0 0.0 0.0
half1 and half2
FAILED with error: Protocol failed: Dimensions' size cannot be zero nor negative.

Using pattern: '/home/marta/software/scipion3/data/tests/model_building_tutorial/volumes/emd_3488.map'
Traceback (most recent call last):
File "/home/marta/software/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
self._run()
File "/home/marta/software/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
resultFiles = self._runFunc()
File "/home/marta/software/scipion3/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
return self._func(*self._args)
File "/home/marta/software/scipion3/scipion-em/pwem/protocols/protocol_import/volumes.py", line 188, in importVolumesStep
samplingRate, emconv.Ccp4Header.ORIGIN)
File "/home/marta/software/scipion3/scipion-em/pwem/convert/headers.py", line 338, in fixFile
ImageHandler().convert(inFileName, outFileName)
File "/home/marta/software/scipion3/scipion-em/pwem/emlib/image/image_handler.py", line 160, in convert
self._img.read(inputLoc)
xmipp.XmippError: Dimensions' size cannot be zero nor negative.
Protocol failed: Dimensions' size cannot be zero nor negative.
FAILED: importVolumesStep, step 1
2020-05-06 08:46:47.102585
*** Last status is failed
------------------- PROTOCOL FAILED (DONE 1/1)
[ FAILED ] TestValCryoEM.testValCryoEMFFromVolumeAndPDB4

**Comment by pconesa** [comment]
This is nos happening to me. It might be fixed?
@mmmtnez ?

**Comment by pconesa** [comment]
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
